### ISSUE TITLE
Having a colon in the mod name or version makes PackUpdate cry

### ISSUE THREAD

**Issue by NotActuallyTerry** [XDjackieXD/PackUpdate#18]
Hi,

Turns out if either the mod name or version has a colon within it, PackUpdate will instead do some funky stuff and make files which confuse Windows Explorer etc. like so: 
![1544348097](https://user-images.githubusercontent.com/670020/49695630-d7649100-fbd8-11e8-9ad4-6129f2a13657.png)

The only real indication of this happening is mods complaining about missing dependencies, as the console log says it was downloaded fine.

**Comment by XDjackieXD** [comment]
The easy fix would be to replace the colons with something else during downloading. This is a "it works on my machine", because Windows doesn't like colons in filenames, whereas linux doesn't care, as long as there isn't a slash in the file name so I didn't notice this during testing.
Feel free to PR the neccessary changes ^^

**Comment by Kilobyte22** [comment]
I've had this happen during the rewrite process too. This is now fixed by limiting the set of allowed characters in mod names and stripping the rest. Fix will be shipped with the 3.0 rewrite.
